<MyCheckBox@CheckBox>:
    size_hint_y: None
    height: '48dp'

ShowcaseScreen:
    name: 'CheckBoxes'

    GridLayout:

        cols: 3
        spacing: '8dp'
        size_hint: .5, None
        height: self.minimum_height

        Label:
            text: 'Checkbox'

        MyCheckBox:

        MyCheckBox:

        Label:
            text: 'CheckBox with group'

        MyCheckBox:
            group: 'g2'

        MyCheckBox:
            group: 'g2'
